name: Gitleaks Scan
on: [push]

jobs:
  scan:
    name: Gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Gitleaks
        run: |
          VERSION="8.18.2"
          wget https://github.com/gitleaks/gitleaks/releases/download/v${VERSION}/gitleaks_${VERSION}_linux_x64.tar.gz
          tar -xf gitleaks_${VERSION}_linux_x64.tar.gz
          sudo mv gitleaks /usr/local/bin/

      - name: Run Gitleaks Scan
        # O comando 'detect' com '--no-git' vai varrer os arquivos atuais
        run: gitleaks detect --source . --verbose 
        
      - name: Run Script
        env:
          TESTE_SECRET_KEY: ${{ secrets.TESTE_SECRET_KEY }}
        run: python config.py
      
      - name: Install Flake8
        run: pip install flake8

      - name: Run Linting
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
