name: Gitleaks Scan
on: [push]

jobs:
  scan:
    name: Gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Gitleaks
        run: |
          VERSION="8.18.2"
          wget https://github.com/gitleaks/gitleaks/releases/download/v${VERSION}/gitleaks_${VERSION}_linux_x64.tar.gz
          tar -xf gitleaks_${VERSION}_linux_x64.tar.gz
          sudo mv gitleaks /usr/local/bin/

      - name: Run Gitleaks Scan
        # O comando 'detect' com '--no-git' vai varrer os arquivos atuais
        run: gitleaks detect --source . --no-git --verbose 
        
      - name: Run Script
        env:
          MINHA_CHAVE_SECRETA: ${{ secrets.TESTE_SECRET_KEY }}
        run: python config.py

      - name: Force Clean and List
        run: |
          # Remove arquivos que não estão rastreados pelo Git
          git clean -fdx 
          # Lista os arquivos para termos certeza do que o Gitleaks vai ver
          ls -R