name: Gitleaks Scan
on: [push]

jobs:
  scan:
    name: Gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Gitleaks
        run: |
          VERSION="8.18.2"
          wget https://github.com/gitleaks/gitleaks/releases/download/v${VERSION}/gitleaks_${VERSION}_linux_x64.tar.gz
          tar -xf gitleaks_${VERSION}_linux_x64.tar.gz
          sudo mv gitleaks /usr/local/bin/

      - name: Hard Reset and Scan
        run: |
          # Remove tudo que não está no último commit
          git clean -fdx
          git reset --hard HEAD
          
          echo "--- Verificando arquivos restantes ---"
          ls -R
          
          # Roda o scan apenas no diretório atual, sem olhar histórico
          gitleaks detect --source . --no-git --verbose
      - name: Run Script
        env:
          MINHA_CHAVE_SECRETA: ${{ secrets.TESTE_SECRET_KEY }}
        run: python config.py
