name: Security Scan
on: [push]

jobs:
  scan:
    name: Scan de segurança do código Labs
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - uses: actions/checkout@v4

      - name: Install Gitleaks
        run: |
          VERSION="8.18.2"
          wget https://github.com/gitleaks/gitleaks/releases/download/v${VERSION}/gitleaks_${VERSION}_linux_x64.tar.gz
          tar -xf gitleaks_${VERSION}_linux_x64.tar.gz
          sudo mv gitleaks /usr/local/bin/

      - name: Run Gitleaks Scan
        # O comando 'detect' com '--no-git' vai varrer os arquivos atuais
        run: gitleaks detect --source . --verbose 
        continue-on-error: true
      
      - name: Snyk Open Source Check
        uses: snyk/actions/python@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high
        
      - name: Iniciar CodeQL Scan
        uses: github/codeql-action/init@v4
        with:
          languages: python
      
      - name: Perform CodeQL Analysis 
        uses: github/codeql-action/analyze@v4

      - name: Run Script
        env:
          TESTE_SECRET_KEY: ${{ secrets.TESTE_SECRET_KEY }}
        run: python config.py
      
