name: Security Scan
on: [push]

jobs:
  scan:
    name: Gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Gitleaks
        run: |
          VERSION="8.18.2"
          wget https://github.com/gitleaks/gitleaks/releases/download/v${VERSION}/gitleaks_${VERSION}_linux_x64.tar.gz
          tar -xf gitleaks_${VERSION}_linux_x64.tar.gz
          sudo mv gitleaks /usr/local/bin/

      - name: Run Gitleaks Scan
        # O comando 'detect' com '--no-git' vai varrer os arquivos atuais
        run: gitleaks detect --source . --verbose 
      
      - name: Snyk Open Source Check
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high
          
      - name: Run Script
        env:
          TESTE_SECRET_KEY: ${{ secrets.TESTE_SECRET_KEY }}
        run: python config.py
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Lint with flake8
        run: |
          # Para o build se houver erros de sintaxe Python ou nomes indefinidos
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # Avisos de estilo (opcional: pode ser configurado para n√£o travar o build)
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
