name: Gitleaks Scan
on: [push]

jobs:
  scan:
    name: Gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Gitleaks
        run: |
          VERSION="8.18.2"
          wget https://github.com/gitleaks/gitleaks/releases/download/v${VERSION}/gitleaks_${VERSION}_linux_x64.tar.gz
          tar -xf gitleaks_${VERSION}_linux_x64.tar.gz
          sudo mv gitleaks /usr/local/bin/

      - name: Run Gitleaks Scan
        # O comando 'detect' com '--no-git' vai varrer os arquivos atuais
        run: gitleaks detect --source . --no-git --verbose 
      - name: Debug README content
        run: |
          echo "--- Linha 42 ---"
          sed -n '42p' README.md
          echo "--- Linhas 221-223 ---"
          sed -n '221,223p' README.md
          echo "--- Linha 259 ---"
          sed -n '259p' README.md
      - name: Run Script
        env:
          MINHA_CHAVE_SECRETA: ${{ secrets.TESTE_SECRET_KEY }}
        run: python config.py